- name: registration.registries.ca
  version: '1.0.39'
  attributes:
    registration_id:
      description: Registration/Incorporation Number or Identifying Number
      required: true
    registration_date:
      description: Date of Registration, Incorporation, Continuation or Amalgamation
      required: false
    registration_expiry_date:
      description: Date the registration will expire (unless extended)
      required: false
    registration_renewal_effective:
      description: Date the registration renewal became effective
      required: false
    entity_name:
      description: The legal name of entity
      required: true
    entity_name_effective:
      description: Date current name became effective
      required: true
    entity_name_assumed:
      description: A legal name used by an extraprovincial company when the home jurisdiction name is not available
      required: false
    entity_name_assumed_effective:
      description: Date assumed name became effective
      required: false
    entity_name_trans:
      description: Entity name translated into another language
      required: false
    entity_name_trans_effective:
      description: Date translated name became effective
      required: false
    entity_status:
      description: Status of the entity (active or historical)
      required: true
    entity_status_effective:
      description: Date status became effective
      required: true
    entity_type:
      description: Type of entity incorporated or registered
      required: true
    registered_jurisdiction:
      description: The jurisdiction an entity was created in
      required: false
    extra_jurisdictional_registration:
      description: Flag to indicate extra-jurisdictional registrations
      required: false
    home_jurisdiction:
      description: Name of home jurisdiction where org is registered
      required: true
    effective_date:
      description: Date Credential is effective
      required: true
    reason_description:
      description: Reason for credential issue/update
      required: false
    expiry_date:
      description: Date Credential expired
      required: true

- name: address.registries.ca
  version: '1.0.39'
  attributes:
    registration_id:
      description: Unique identifer assigned to entity by registrar
      required: true
    addressee:
      description: Legal and principle name assigned to entity by registrar
      required: true
    address_type:
      description: Type designator for this address
      required: true
    civic_address:
      description: Street number, name, direction, suite, etc.
      required: true
    municipality:
      description: Name of a recognized municipality
      required: true
    province:
      description: Name of recognized sub-national territory
      required: true
    postal_code:
      description: Identifier issued by postal agency
      required: true
    country:
      description: Name of a recognized national territory
      required: true
    address_effective_date:
      description: Date current address became/becomes effective
      required: false
    effective_date:
      description: Date Credential is effective
      required: true
    expiry_date:
      description: Date Credential expires
      required: false
    reason_description:
      description: Reason for credential issue/update
      required: false

- name: relationship.registries.ca
  version: '1.0.39'
  attributes:
    registration_id:
      description: Unique identifer assigned to entity by registrar
      required: true
    associated_registration_id:
      description: Registry id(s) of associated organizations/individuals
      required: true
    relationship:
      description: Name of the relationship
      required: true
    relationship_description:
      description: Description of the relationship
      required: true
    relationship_status:
      description: Status of the relationship
      required: true
    relationship_status_effective:
      description: Date the relationship became/becomes effective
      required: false
    effective_date:
      description: Date Credential is effective
      required: true
    expiry_date:
      description: Date Credential expires
      required: false
    reason_description:
      description: Reason for credential issue/update
      required: false
