- name: registration.registries.ca
  version: '1.0.40'
  attributes:
    registration_id:
      label_en: Registration ID
      description_en: Registration/Incorporation Number or Identifying Number
      required: true
    registration_date:
      label_en: Registration Date
      description_en: Date of Registration, Incorporation, Continuation or Amalgamation
      required: false
    registration_expiry_date:
      label_en: Registration Expiry Date
      description_en: Date the registration will expire (unless extended)
      required: false
    registration_renewal_effective:
      label_en: Registration Renewal Effective
      description_en: Date the registration renewal became effective
      required: false
    entity_name:
      label_en: Name
      description_en: The legal name of entity
      required: true
    entity_name_effective:
      label_en: Name Effective Date
      description_en: Date current name became effective
      required: true
    entity_name_assumed:
      label_en: Assumed Name
      description_en: A legal name used by an extraprovincial company when the home jurisdiction name is not available
      required: false
    entity_name_assumed_effective:
      label_en: Assumed Name Effective Date
      description_en: Date assumed name became effective
      required: false
    entity_name_trans:
      label_en: Translated Name
      description_en: Entity name translated into another language
      required: false
    entity_name_trans_effective:
      label_en: Translated Name Effective Date
      description_en: Date translated name became effective
      required: false
    entity_status:
      label_en: Registration Status
      description_en: Status of the entity (active or historical)
      required: true
    entity_status_effective:
      label_en: Status Effective Date
      description_en: Date status became effective
      required: true
    entity_type:
      label_en: Registration Type
      description_en: Type of entity incorporated or registered
      required: true
    registered_jurisdiction:
      label_en: Registered Jurisdiction
      description_en: The jurisdiction an entity was created in
      required: false
    extra_jurisdictional_registration:
      label_en: Extra-Jurisdictional Registration
      description_en: Flag to indicate extra-jurisdictional registrations
      required: false
    home_jurisdiction:
      label_en: Home Jurisdiction
      description_en: Name of home jurisdiction where org is registered
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      required: true
    reason_description:
      label_en: Credential Issue Reason
      description_en: Reason for credential issue/update
      required: false
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expired
      required: true

- name: address.registries.ca
  version: '1.0.40'
  attributes:
    registration_id:
      label_en: Registration ID
      description_en: Unique identifer assigned to entity by registrar
      required: true
    addressee:
      label_en: Addressee
      description_en: Legal and principle name assigned to entity by registrar
      required: true
    address_type:
      label_en: Address Type
      description_en: Type designator for this address
      required: true
    civic_address:
      label_en: Civic Address
      description_en: Street number, name, direction, suite, etc.
      required: true
    municipality:
      label_en: Municipality
      description_en: Name of a recognized municipality
      required: true
    province:
      label_en: Province
      description_en: Name of recognized sub-national territory
      required: true
    postal_code:
      label_en: Postal Code
      description_en: Identifier issued by postal agency
      required: true
    country:
      label_en: Country
      description_en: Name of a recognized national territory
      required: true
    address_effective_date:
      label_en: Address Effective Date
      description_en: Date current address became/becomes effective
      required: false
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      required: true
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expires
      required: false
    reason_description:
      label_en: Credential Issue Reason
      description_en: Reason for credential issue/update
      required: false

- name: relationship.registries.ca
  version: '1.0.40'
  attributes:
    registration_id:
      label_en: Registration ID
      description_en: Unique identifer assigned to entity by registrar
      required: true
    associated_registration_id:
      label_en: Associated Registration ID
      description_en: Registry id(s) of associated organizations/individuals
      required: true
    relationship:
      label_en: Relationship
      description_en: Name of the relationship
      required: true
    relationship_description:
      label_en: Relationship Description
      description_en: Description of the relationship
      required: true
    relationship_status:
      label_en: Relationship Status
      description_en: Status of the relationship
      required: true
    relationship_status_effective:
      label_en: Relationship Status Effective
      description_en: Date the relationship became/becomes effective
      required: false
    effective_date:
      label_en: Registration ID
      description_en: Date Credential is effective
      required: true
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expires
      required: false
    reason_description:
      label_en: Credential Issue Reason
      description_en: Reason for credential issue/update
      required: false
